// Generated by design/generate.py from design/tokens.json. Do not edit.
pragma Singleton

import QtQuick
import Quickshell

Singleton {
    // Dark is the default look for the shell; Settings will toggle this later.
    property bool dark: true

    readonly property color background: dark ? "#121418" : "#F5F6F8"
    readonly property color surface: dark ? "#1B1E24" : "#FFFFFF"
    readonly property color surfaceAlt: dark ? "#242830" : "#ECEEF2"
    readonly property color border: dark ? "#2F343D" : "#DDE1E7"
    readonly property color text: dark ? "#E8EBF0" : "#1B1F27"
    readonly property color textMuted: dark ? "#9AA3B2" : "#5B6474"
    readonly property color accent: dark ? "#9D96FF" : "#5B52D6"
    readonly property color accentText: dark ? "#14121F" : "#FFFFFF"
    readonly property color good: dark ? "#4CC38A" : "#1F8A57"
    readonly property color warn: dark ? "#E5A443" : "#9A5C00"
    readonly property color bad: dark ? "#F0716A" : "#C8372D"

    readonly property int radiusSmall: 8
    readonly property int radiusMedium: 12
    readonly property int radiusLarge: 20
    readonly property int radiusPill: 999

    readonly property int spacingXs: 4
    readonly property int spacingS: 8
    readonly property int spacingM: 12
    readonly property int spacingL: 16
    readonly property int spacingXl: 24
    readonly property int spacingXxl: 32

    readonly property string fontDisplay: "Lexend"
    readonly property string fontUi: "Figtree"
    readonly property string fontMono: "JetBrains Mono"
    readonly property int fontSizeSmall: 12
    readonly property int fontSizeBody: 14
    readonly property int fontSizeTitle: 18
    readonly property int fontSizeDisplay: 28

    readonly property int motionFast: 120
    readonly property int motionNormal: 200
    readonly property int motionSlow: 320

    readonly property int barHeight: 36
    readonly property int barGap: 8
}
