#!/usr/bin/env python3
"""Generate SoftRock theme files from design/tokens.json.

Every color, radius and tier setting the desktop uses comes from tokens.json.
This script turns it into the formats each component reads: a QML singleton
for SoftRock Shell, Hyprland config snippets, GTK CSS and a Foot config.

Usage:
    generate.py           write all generated files
    generate.py --check   exit 1 if any generated file is out of date
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "design" / "tokens.json"
CHROOT = ROOT / "iso" / "config" / "includes.chroot"
SKEL = CHROOT / "etc" / "skel" / ".config"
SHARE = CHROOT / "usr" / "share" / "softrock"

HEADER = "Generated by design/generate.py from design/tokens.json. Do not edit."


def load_tokens(path=TOKENS):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def hex6(color):
    """'#5B52D6' -> '5b52d6'"""
    return color.lstrip("#").lower()


def qml_theme(t):
    lines = [
        f"// {HEADER}",
        "pragma Singleton",
        "",
        "import QtQuick",
        "import Quickshell",
        "",
        "Singleton {",
        "    // Dark is the default look for the shell; Settings will toggle this later.",
        "    property bool dark: true",
        "",
    ]
    for name, pair in t["colors"].items():
        lines.append(
            f'    readonly property color {name}: dark ? "{pair["dark"]}" : "{pair["light"]}"'
        )
    lines.append("")
    for group in ("radius", "spacing"):
        for name, value in t[group].items():
            prop = group + name[0].upper() + name[1:]
            lines.append(f"    readonly property int {prop}: {value}")
        lines.append("")
    font = t["font"]
    lines.append(f'    readonly property string fontDisplay: "{font["display"]}"')
    lines.append(f'    readonly property string fontUi: "{font["ui"]}"')
    lines.append(f'    readonly property string fontMono: "{font["mono"]}"')
    for name, value in font["size"].items():
        lines.append(f"    readonly property int fontSize{name[0].upper() + name[1:]}: {value}")
    lines.append("")
    for name, value in t["motion"].items():
        lines.append(f"    readonly property int motion{name[0].upper() + name[1:]}: {value}")
    lines.append("")
    lines.append(f'    readonly property int barHeight: {t["bar"]["height"]}')
    lines.append(f'    readonly property int barGap: {t["bar"]["gap"]}')
    lines.append("}")
    return "\n".join(lines) + "\n"


def hypr_colors(t):
    lines = [f"# {HEADER}", ""]
    for name, pair in t["colors"].items():
        lines.append(f"$sr_{name} = rgb({hex6(pair['dark'])})")
        lines.append(f"$sr_{name}_light = rgb({hex6(pair['light'])})")
    lines += [
        "",
        "general {",
        "    col.active_border = $sr_accent",
        "    col.inactive_border = $sr_border",
        "}",
    ]
    return "\n".join(lines) + "\n"


def hypr_tier(t, tier_name):
    tier = t["tiers"][tier_name]
    on = lambda b: "true" if b else "false"
    speed = tier["animationSpeed"]
    return "\n".join([
        f"# {HEADER}",
        f"# Visual tier: {tier_name}",
        "",
        "general {",
        f"    gaps_in = {tier['gapsIn']}",
        f"    gaps_out = {tier['gapsOut']}",
        "    border_size = 1",
        "}",
        "",
        "decoration {",
        f"    rounding = {t['radius']['medium']}",
        "    blur {",
        f"        enabled = {on(tier['blur'])}",
        f"        size = {max(tier['blurSize'], 1)}",
        f"        passes = {max(tier['blurPasses'], 1)}",
        "    }",
        "    shadow {",
        f"        enabled = {on(tier['shadow'])}",
        f"        range = {max(tier['shadowRange'], 1)}",
        "        render_power = 3",
        "        color = rgba(00000050)",
        "    }",
        "}",
        "",
        "animations {",
        "    enabled = true",
        "    bezier = softrock, 0.2, 0.9, 0.1, 1.0",
        f"    animation = windows, 1, {speed}, softrock, popin 90%",
        f"    animation = fade, 1, {speed}, softrock",
        f"    animation = workspaces, 1, {speed}, softrock, slide",
        "}",
    ]) + "\n"


def gtk_css(t, gtk4):
    c = {k: v["dark"] for k, v in t["colors"].items()}
    if gtk4:
        pairs = [
            ("accent_color", c["accent"]),
            ("accent_bg_color", c["accent"]),
            ("accent_fg_color", c["accentText"]),
            ("window_bg_color", c["background"]),
            ("window_fg_color", c["text"]),
            ("view_bg_color", c["surface"]),
            ("view_fg_color", c["text"]),
            ("headerbar_bg_color", c["surface"]),
            ("headerbar_fg_color", c["text"]),
            ("sidebar_bg_color", c["surfaceAlt"]),
            ("sidebar_fg_color", c["text"]),
            ("card_bg_color", c["surface"]),
            ("card_fg_color", c["text"]),
            ("popover_bg_color", c["surface"]),
            ("popover_fg_color", c["text"]),
            ("dialog_bg_color", c["surface"]),
            ("dialog_fg_color", c["text"]),
            ("success_color", c["good"]),
            ("warning_color", c["warn"]),
            ("error_color", c["bad"]),
        ]
    else:
        pairs = [
            ("theme_bg_color", c["background"]),
            ("theme_fg_color", c["text"]),
            ("theme_base_color", c["surface"]),
            ("theme_text_color", c["text"]),
            ("theme_selected_bg_color", c["accent"]),
            ("theme_selected_fg_color", c["accentText"]),
            ("insensitive_fg_color", c["textMuted"]),
            ("borders", c["border"]),
            ("success_color", c["good"]),
            ("warning_color", c["warn"]),
            ("error_color", c["bad"]),
        ]
    lines = [f"/* {HEADER} */"]
    lines += [f"@define-color {name} {value};" for name, value in pairs]
    return "\n".join(lines) + "\n"


def foot_ini(t):
    term = t["terminal"]["dark"]
    lines = [
        f"# {HEADER}",
        "",
        "[main]",
        f"font={t['font']['mono']}:size=11",
        "pad=12x12",
        "",
        "[colors]",
        f"background={hex6(term['background'])}",
        f"foreground={hex6(term['foreground'])}",
    ]
    for i, color in enumerate(term["regular"]):
        lines.append(f"regular{i}={hex6(color)}")
    for i, color in enumerate(term["bright"]):
        lines.append(f"bright{i}={hex6(color)}")
    return "\n".join(lines) + "\n"


def fuzzel_ini(t):
    c = {k: hex6(v["dark"]) for k, v in t["colors"].items()}
    return "\n".join([
        f"# {HEADER}",
        "",
        "[main]",
        f"font={t['font']['ui']}:size=12",
        "terminal=foot",
        "layer=overlay",
        "width=40",
        "lines=10",
        "horizontal-pad=16",
        "vertical-pad=12",
        "",
        "[colors]",
        f"background={c['surface']}f2",
        f"text={c['text']}ff",
        f"prompt={c['textMuted']}ff",
        f"input={c['text']}ff",
        f"match={c['accent']}ff",
        f"selection={c['surfaceAlt']}ff",
        f"selection-text={c['text']}ff",
        f"selection-match={c['accent']}ff",
        f"border={c['border']}ff",
        "",
        "[border]",
        f"radius={t['radius']['large']}",
        "width=1",
    ]) + "\n"


def mako_config(t):
    c = {k: v["dark"] for k, v in t["colors"].items()}
    return "\n".join([
        f"# {HEADER}",
        f"font={t['font']['ui']} 11",
        f"background-color={c['surface']}",
        f"text-color={c['text']}",
        f"border-color={c['border']}",
        f"progress-color=over {c['accent']}",
        f"border-radius={t['radius']['medium']}",
        "border-size=1",
        f"padding={t['spacing']['m']}",
        f"margin={t['spacing']['m']}",
        "width=360",
        "default-timeout=5000",
        "",
        "[urgency=critical]",
        f"border-color={c['bad']}",
        "default-timeout=0",
    ]) + "\n"


def outputs(t):
    """Map of output path -> file content."""
    files = {
        ROOT / "shell" / "Theme.qml": qml_theme(t),
        SHARE / "hypr" / "colors.conf": hypr_colors(t),
        SKEL / "gtk-3.0" / "gtk.css": gtk_css(t, gtk4=False),
        SKEL / "gtk-4.0" / "gtk.css": gtk_css(t, gtk4=True),
        SKEL / "foot" / "foot.ini": foot_ini(t),
        SKEL / "fuzzel" / "fuzzel.ini": fuzzel_ini(t),
        SKEL / "mako" / "config": mako_config(t),
    }
    for tier in t["tiers"]:
        files[SHARE / "hypr" / f"tier-{tier}.conf"] = hypr_tier(t, tier)
    return files


def main(argv):
    check = "--check" in argv
    stale = []
    for path, content in outputs(load_tokens()).items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("Out of date, run make tokens:", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
